//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica3.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticaS13Entities : DbContext
    {
        public PracticaS13Entities()
            : base("name=PracticaS13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonos> Abonos { get; set; }
        public virtual DbSet<Principal> Principal { get; set; }
    
        public virtual ObjectResult<SP_ConsultarProductos_Result> SP_ConsultarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarProductos_Result>("SP_ConsultarProductos");
        }
    
        public virtual ObjectResult<SP_ConsultarComprasPendientes_Result> SP_ConsultarComprasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarComprasPendientes_Result>("SP_ConsultarComprasPendientes");
        }
    
        public virtual ObjectResult<SP_ConsultarSaldo_Result> SP_ConsultarSaldo(Nullable<long> id_Compra)
        {
            var id_CompraParameter = id_Compra.HasValue ?
                new ObjectParameter("Id_Compra", id_Compra) :
                new ObjectParameter("Id_Compra", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarSaldo_Result>("SP_ConsultarSaldo", id_CompraParameter);
        }
    
        public virtual ObjectResult<SP_RegistrarAbono_Result> SP_RegistrarAbono(Nullable<long> id_Compra, Nullable<decimal> monto)
        {
            var id_CompraParameter = id_Compra.HasValue ?
                new ObjectParameter("Id_Compra", id_Compra) :
                new ObjectParameter("Id_Compra", typeof(long));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RegistrarAbono_Result>("SP_RegistrarAbono", id_CompraParameter, montoParameter);
        }
    }
}
